[cfg]
# 0: no erase, 1: programmed section erase, 2: chip erase
erase = 1
# skip mode first parameter is skip address, second parameter is skip length
skip_mode = 0x0, 0x0
# 0: do not use isp mode, 1: use isp mode
boot2_isp_mode = 0

[FW]
filedir = ./build/build_out/m61_dualsense_hidp_probe_$(CHIPNAME)*.bin
address = 0x000000
